sonar.projectKey=junioeusebio_handily-commerce-frontend
sonar.organization=junioeusebio
sonar.projectName=handily-commerce-frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.js
sonar.javascript.lcov.reportPaths=coverage/handily-commerce-frontend/lcov.info
sonar.typescript.lcov.reportPaths=coverage/handily-commerce-frontend/lcov.info
sonar.coverage.exclusions=**/*.spec.ts,**/main.ts,**/index.ts
